//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Maze
//  @ File Name : Door.cs
//  @ Date : 29.11.2018
//  @ Author : DKu
//
//

using System;

namespace Maze
{
	public class Door : MapSite{
		public bool IsOpen ;
        private Room r1;
        private Room r2;

        public Door(Room r1, Room r2)
        {
            this.r1 = r1;
            this.r2 = r2;
        }

        public override void Enter(){
			Console.WriteLine($"Przechodzę przez drzwi.");
		}
	}
}