//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Maze
//  @ File Name : MapSite.cs
//  @ Date : 29.11.2018
//  @ Author : DKu
//
//

namespace Maze
{
	public abstract class MapSite {
		public abstract void Enter();
	}
}