//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Maze
//  @ File Name : Maze.cs
//  @ Date : 29.11.2018
//  @ Author : DKu
//
//

using System;
using System.Collections.Generic;

namespace Maze
{
		public class Maze {
		public List<Room> rooms = new List<Room>();
		public void AddRoom(Room room){
			rooms.Add(room);
		}
		public Room RoomNo(int roomNo){
			return rooms.Find(x=>x.roomNumber == roomNo);
		}
		public void Play()
		{
			
		}

		public void ShowMaze()
		{
			foreach (var item in rooms)
			{
				Console.WriteLine($"Maze contain room no {item.roomNumber}.");
				foreach (var side in item.sides)
				{
					Console.WriteLine($"Room no {item.roomNumber} contain site {side.Value} on {side.Key}.");
				}
			}
		}
	}
}