//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Maze
//  @ File Name : Room.cs
//  @ Date : 29.11.2018
//  @ Author : DKu
//
//

using System;
using System.Collections.Generic;

namespace Maze
{
	public class Room : MapSite{
		public int roomNumber ;
		public Dictionary<Direction,MapSite> sides = new Dictionary<Direction, MapSite>();

        internal void SetSide(Direction direction, MapSite mapSite)
        {
			if(sides.ContainsKey(direction))
				sides[direction] = mapSite;
			else
            	sides.Add(direction,mapSite);
        }

		internal MapSite GetSide(Direction direction)
		{
			return sides[direction];
		}

        public Room(int roomNumber)
        {
            this.roomNumber = roomNumber;
        }

		public override void Enter(){
			Console.WriteLine($"Jestem w pokoju nr {roomNumber}");
		}
	}
}