//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Maze
//  @ File Name : Wall.cs
//  @ Date : 29.11.2018
//  @ Author : DKu
//
//

using System;

namespace Maze
{
	public class Wall : MapSite{
		public override void Enter(){
			Console.WriteLine($"Udeżyłem w ścianę -2 HP");
		}
	}
}